### ISSUE TITLE
Modular support for hardware devices

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-FirmwareSource#206]
There is probably no single Mobiflight board that will use all the support built into it.  Yet, I believe that the lack of memory space is hindering any future development.  It seems that a modular approach - where you can pick your devices that you want to use and build the firmware you need for the panel you plan - would greatly expand the flexibility.  A user may want to load a large module that only supports for example graphical OLED displays into a pro micro board.
I know the convenience of having only one firmware version makes it easier to maintain, but at the expense of not being able to grow.  It becomes very expensive to carry support for things you don't need.
IMHO even moving to a larger capacity board, only buys some time, before we find ourselves limited again.
Maybe a "core" functionality for buttons and leds can be left in all firmware, everything else being optional, until you fill available memory.

**Comment by DocMoebiuz** [comment]
@JaimeLeon2 Thanks for creating an explicit issue for this. 
I think there are two aspects in here: 

- Enable/disable certain devices to save RAM for other devices
- Allow for custom devices

Since it will involve the Connector too, i will mainly keep track of the progress in [MobiFlight-Connector](https://github.com/MobiFlight/MobiFlight-Connector).

Issue Custom Devices:
https://github.com/MobiFlight/MobiFlight-Connector/issues/331
